### ISSUE TITLE
Losted phone

### ISSUE THREAD

**Issue by maxsanA47** [transitland/dispatcher#102]
I recently losted my phone in Moscau and cant recover more my old google acaount, and old gmail with lots activity on it, vkadimirmaksimovicmax@gmail.com, evreting is losted all my projects with my google pages and youtube chanel,is sombody there who can help me to recover all i tryed all but nothing works to recover this mail, :(((

**Comment by maxsanA47** [comment]
Now i hawe new phone but google simply puted all under one pasword

**Comment by drewda** [comment]
Spam.

**Comment by maxsanA47** [comment]
what is spam is you crazy i losted all on this api phone

**Comment by maxsanA47** [comment]
and me is hacked from one crazy hacker on my original google gmail andvgoogle+ acaount and himbyryvall timevagain to hack me to fucking hell and nobody help me outbfromngooglevand gmail tim

**Comment by maxsanA47** [comment]
blow mevidiot i am hacked totaly on this mail and losted lots earnings
there sayvwhat you want asshole

19.08.2016. 17.44, "Drew Dara-Abrams" <notifications@github.com> је
написао/ла:
