### ISSUE TITLE
Feed page not loading: empty ?feed_version_sha1 query

### ISSUE THREAD

**Issue by irees** [transitland/dispatcher#237]
FeedVersionInfos: ?feed_version_sha1 is empty

See: https://github.com/transitland/transitland-datastore/issues/1116

Example:
https://transit.land/dispatcher/feeds/f-f25d-agencemétropolitainedetransportexpress

**Comment by drewda** [comment]
Also occurs on https://transit.land/dispatcher/feeds/f-sv-%D7%92%D7%9C%D7%99%D7%9D~%D7%9E%D7%95%D7%A2%D7%A6%D7%94%D7%90%D7%96%D7%95%D7%A8%D7%99%D7%AA%D7%92%D7%95%D7%9C%D7%9F~%D7%90%D7%A4%D7%99%D7%A7%D7%99%D7%9D~%D7%93%D7%9F%D7%A6%D7%A4%D7%95%D7%9F~%D7%93%D7%9F%D7%91%D7%93%D7%A8%D7%95%D7%9D~%D7%93%D7%9F%D7%91%D7%90%D7%A8%D7%A9%D7%91%D7%A2~%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D
