### ISSUE TITLE
view, resolve, and create Issues

### ISSUE THREAD

**Issue by drewda** [transitland/dispatcher#58]
a front-end interface to https://github.com/transitland/transitland-datastore/issues/569

**Comment by doublestranded** [comment]
Items to do for view:

- [ ] display stop distances on distance issues
- [ ] leaflet measure tool.
- [ ] map layers as layer group.
- [ ] removal of existing layers when new issue clicked.
- [ ] map zoom on issue click
- [ ] issue id in URL
- [ ] map entities (layers) need popup
- [ ] Save button whose click action results in changeset and changeset apply.
- [ ] Styling. Leaflet map needs height percentage. Issue column on left, map and details on right
- [ ] Testing

**Comment by doublestranded** [comment]
For issue creation, the hierarchical view from route-spotter will be borrowed, and the user will be presented a button to create issues from.

**Comment by doublestranded** [comment]
Question: how to structure/separate issues viewing from route geometry editing and changeset resolution creation. Should route geometry editing (both rsps and stops) for a changeset live on a separate route or at least component? A link from a particular issue?

**Comment by doublestranded** [comment]
Stop distance matching to RSP polyline should be done in a separate Leaflet control plugin

**Comment by doublestranded** [comment]
Appears to be a bug in create issues, where an entity with issue of another issue is reassigned to the new issue. It could just be a dispatcher issues page bug.

**Comment by doublestranded** [comment]
Feed onestop id as query parameter?

**Comment by doublestranded** [comment]
Make sure to allow > 50 issues per one request
