### ISSUE TITLE
Quickly view geographic extent of a feed

### ISSUE THREAD

**Issue by stevevance** [transitland/dispatcher#86]
While I'm reviewing the feed submissions, it's helpful to see the geographic area covered by each operator in the feed. This helps me determine the metro area and state/province for unfamiliar places around the world. 

Currently I copy and paste the `geometry` object into [geojson.io](http://geojson.io).

**Comment by stevevance** [comment]
A minor step would be to cast the coordinates as floats. Sometimes they appear as strings and I have to remove the quotes to be able to visualize the shape in GeoJSON.io.

**Comment by drewda** [comment]
The minor step: https://github.com/transitland/transitland-datastore/issues/695

**Comment by stevevance** [comment]
In the meantime, use this regex to remove quotes from the coordinates: `\"(\-?\d+\.\d+)\"`
